"""
Claude XML output validation.
Checks required modules are present and non-trivially short.
Falls back to placeholder text per module if missing.
"""

REQUIRED_MODULES = ["module_2", "module_5", "module_6"]
MIN_LENGTH = {
    "module_2": 1,
    "module_5": 0,   # empty list is fine — format_module_5 shows clean "no items" message
    "module_6": 30,
}

FALLBACK_TEXT = {
    "module_2": [
        {
            "headline": "[Synthesis unavailable]",
            "body": "Claude synthesis failed for this module. Check admin logs.",
            "so_what": "Unable to generate book implication.",
        }
    ],
    "module_5": [],  # empty — format_module_5 handles this gracefully
    "module_6": "[Contrarian Corner unavailable — synthesis failed]",
    "module_4_caption": "Chart generated by rules-based selection.",
}


def validate_output(parsed: dict) -> dict:
    """Ensure all required modules are present with sufficient content."""
    for module in REQUIRED_MODULES:
        value = parsed.get(module)
        if not value:
            parsed[module] = FALLBACK_TEXT[module]
            continue
        if isinstance(value, list) and len(value) < MIN_LENGTH.get(module, 1):
            parsed[module] = FALLBACK_TEXT[module]
        elif isinstance(value, str) and len(value) < MIN_LENGTH.get(module, 0):
            parsed[module] = FALLBACK_TEXT[module]

    if not parsed.get("module_4_caption"):
        parsed["module_4_caption"] = FALLBACK_TEXT["module_4_caption"]

    return parsed
